### ISSUE TITLE
Set-Up confusion

### ISSUE THREAD

**Issue by SlickStretch** [andrewelick/amazon-giveaway-bot#8]
I'm having trouble with step 5 of set up.

> 5: Change the PATH of the variable profile to the path of the Firefox profile the you just created. profile = webdriver.FirefoxProfile(''). This will allow you stay logged in to your Amazon account and run the program in headless mode. If you do not do this you will need to change the line options.headless = True to options.headless = False

Where can I find this variable? Is is a windows system variable? Is it in Firefox? Python? How do I go about finding and changing it?

**Comment by ryanrohypnol** [comment]
Did you figure it out? If not, just find the Firefox profile you created (you must show hidden files on windows) and copy the address and just replace his with yours in the python script.

**Comment by SlickStretch** [comment]
Oh, it's in *amazoncontest.py*. That makes sense, and seems obvious to me now. I was looking for a system variable...

Thank you ryanrohypnol. I didn't know if I would get any response.
